### PR TITLE
Use immediate library for asynchronous invokes.

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by juliangruber** [comment]
can you explain why you need this change?

**Comment by calvinmetcalf** [comment]
I will point out also that the queue system of immediate is now in
browserify's process.nextTick, so using immediate is likely no longer an
advantage.

**Comment by ronag** [comment]
In web pack it is a lot faster.

**Comment by calvinmetcalf** [comment]
That seems like an issue to open with Web pack

**Comment by ronag** [comment]
Fair enough.

**Comment by calvinmetcalf** [comment]
If you open an issue on Web pack do link to it here

**Pull request closed without merging**
